### Menachot 70a

**1.**
*Hebrew/Aramaic:* דְּאַמְדִינְהוּ וְעַשְּׂרִינְהוּ וְשַׁתְלִינְהוּ (וְהוֹסִיפָה) [וְאוֹסִיפָא] לְהוּ.
*Translation:* one **estimated** the amount of tithe necessary, **and** then he **separated those tithes, and** then he **planted** the grain again **and** it **added to its** growth. The question is whether we follow the initial growth, and therefore the subsequent growth is exempt from the obligation to separate tithes, or do we follow the additional growth and deem it obligated in tithes?

**2.**
*Hebrew/Aramaic:* אִם תִּמְצָא לוֹמַר, לָא אָזְלִינַן בָּתַר עִיקָּר, וְתוֹסֶפֶת בָּעֵי עַשּׂוֹרֵי – עִיקָּר מַאי? אֲמַר לֵיהּ אַבָּיֵי: מַאי שְׁנָא מִכׇּל חִיטֵּי וּשְׂעָרֵי דְּעָלְמָא?
*Translation:* Rabba adds: **If you say** that **we do not follow the main** growth **and** therefore the **additional** growth **requires** the separation of **tithes, what** is the *halakha* with regard to the **main,** initial growth? Does it require an additional separation of tithes, or does it not, as tithes were already set aside for it? **Abaye said to** Rabba: In **what** way **is** this case **different from any general** case of **wheat or barley?** When grain is tithed and replanted, the obligation of tithes always applies to what then grows.

**3.**
*Hebrew/Aramaic:* אֲמַר לֵיהּ: דָּבָר שֶׁזַּרְעוֹ כָּלֶה – לָא מִיבַּעְיָא לִי, אֶלָּא כִּי קָמִיבַּעְיָא לִי – דָּבָר שֶׁאֵין זַרְעוֹ כָּלֶה, מַאי?
*Translation:* Rabba **said to** Abaye: **I do not raise the dilemma** with regard to **a substance whose seed disintegrates** in the ground. In such a case it is clear that the new growth requires a new tithe to be separated, as the original seed is no longer extant. **Rather, when I raise the dilemma** it is with regard to **a substance whose** original **seed does not disintegrate. What** is the *halakha*? Do we follow the original growth, for which tithes have already been separated, or do we follow the additional growth that is still being generated by that original seed?

**4.**
*Hebrew/Aramaic:* תִּפְשׁוֹט לֵיהּ מֵהָא דְּאָמַר רַבִּי יִצְחָק אָמַר רַבִּי יוֹחָנָן: לִיטְרָא בָּצָל שֶׁתִּיקְּנוֹ וּזְרָעוֹ – מִתְעַשֵּׂר לְפִי כּוּלּוֹ.
*Translation:* The Gemara asks: **Let him resolve** the dilemma **from that which Rabbi Yitzḥak said** that **Rabbi Yoḥanan said:** With regard to **a *litra* of onions that one tithed, and** then he **sowed** a field with the entire *litra* of onions, when the field yields a crop **it is tithed according to the entire** crop. Although some of the onions he sowed were already tithed, he is obligated to tithe them again because the growths exceed the original onions and therefore the entire crop has untithed status.

**5.**
*Hebrew/Aramaic:* הָתָם – הַיְינוּ זְרִיעָתוֹ, הָכָא – לָאו הַיְינוּ זְרִיעָתוֹ.
*Translation:* The Gemara rejects that resolution: **There,** in the case of the field sowed with the tithed onions, the entire field must be tithed because **that is** the normal way in which a field **is sowed.** One generally replants a full onion, and therefore the focus is not on the original onion but on the yield, which must be fully tithed. **Here,** in the case of grain, this **is not** the normal way in which a field **is sowed.** Generally one plants individual kernels, not fully grown ears of grain. Consequently, any subsequent growth from that fully grown ear is considered part of the original growth.

**6.**
*Hebrew/Aramaic:* אֲמַר לֵיהּ רַבִּי חֲנִינָא בַּר מִנְיוֹמֵי לְאַבָּיֵי: עָצִיץ שֶׁאֵינוֹ נָקוּב, מַהוּ? אִי לֹא נָקוּב – הָא לֹא נָקוּב!
*Translation:* **Rabbi Ḥanina bar Minyumi said to Abaye:** In a case of **a flowerpot [*atzitz*] that is not perforated, what is** the *halakha* with regard to separating *teruma* and tithes? Abaye replied: What is the difficulty here? **If it is not perforated, this** *halakha* is the same as that of any **non-perforated** flowerpot, i.e., the separation of *teruma* and tithes is required by rabbinic law.

**7.**
*Hebrew/Aramaic:* דִּלְמָא חָזַר וּנְקָבוֹ, קָא אָמְרַתְּ?
*Translation:* Abaye continues: **Perhaps** what **you** meant to **say** is that he subsequently **went and perforated it.** In such a case the question is whether one may separate *teruma* and tithes from the initial growth of the plant. Is the initial growth considered a separate entity, in which case one part of the growth requires the separation of *teruma* and tithes by rabbinic law and the rest by Torah law, and therefore one may not separate from the initial growth? Alternatively, perhaps the initial growth is nullified by the subsequent growth, which would mean that the obligation of *teruma* and tithes applies to the entire plant by Torah law. Consequently, this obligation can be fulfilled by separating *teruma* and tithes from the initial growth of the plant. This would be similar to Rabba’s dilemma with regard to an ear of grain that is replanted.

**8.**
*Hebrew/Aramaic:* הָכָא, חֲדָא זְרִיעָה הִיא, אִיחַבּוֹרֵי הוּא דְּקָא מִיחַבְּרָא וְעוֹלָה; הָתָם – שְׁתֵּי זְרִיעוֹת נִינְהוּ.
*Translation:* Abaye explains that the two cases are not comparable. **Here,** in the case of the non-perforated flowerpot which was subsequently perforated, it **is one** single **sowing.** Therefore, although the original growth occurred while the pot was not perforated, since it is now perforated, the plant **is** considered **attached** to the ground **and it rises** and grows from there. Consequently, the obligation of *teruma* and tithes applies to the entire plant by Torah law. **There,** in Rabba’s dilemma involving the replanting of an ear of grain, **there are two** distinct **sowings.** Therefore, there is room to debate whether or not the additional, second sowing is part of the original, first sowing.

**9.**
*Hebrew/Aramaic:* בָּעֵי רַבִּי אֲבָהוּ: שִׁבּוֹלֶת שֶׁמֵּרְחָהּ בִּכְרִי, וּשְׁתָלָהּ, וְקָרָא עָלֶיהָ שֵׁם בִּמְחוּבָּר – מַהוּ? כֵּיוָן דְּמֵרְחָהּ טָבְלָא לַהּ, כִּי קָרָא עָלֶיהָ שֵׁם קָדְשָׁה לַהּ, אוֹ דִלְמָא, כֵּיוָן דְּשַׁתְלַהּ – פְּקַע לֵיהּ טִבְלָא מִינַּהּ.
*Translation:* § **Rabbi Abbahu raises a dilemma:** With regard to **an ear** of grain **that one smoothed into a pile and** then **sowed it** again **and** subsequently **designated it** as *teruma* or tithes **while** it was **attached** to the ground, **what is** the *halakha*? Does one say that **since he smoothed it,** which is the act that renders produce subject to the obligation of *teruma* and tithes, **he has given it** the status of **untithed produce, and** therefore **when he** subsequently **designated it he** thereby **sanctified it? Or perhaps, since he** had **sowed it** again after he had smoothed it, **its** status as **untithed produce lapsed from it.**

**10.**
*Hebrew/Aramaic:* אָמְרִי לֵיהּ רַבָּנַן לְאַבָּיֵי: אִם כֵּן, מָצִינוּ תְּרוּמָה בִּמְחוּבָּר לַקַּרְקַע, וּתְנַן: לֹא מָצִינוּ תְּרוּמָה בִּמְחוּבָּר לַקַּרְקַע!
*Translation:* **The Sages said to Abaye: If so,** that the grain is sanctified in this situation, **we** have **found** a case of ***teruma*** that is sanctified while it is still **attached to the ground. But we learn** in a *baraita*: **We do not find** a case of ***teruma* attached to the ground.** Therefore, one must conclude that its status as untithed produce has been removed, and his designation does not render it *teruma*.

**11.**
*Hebrew/Aramaic:* אֲמַר לֵיהּ: כִּי תַּנְיָא הָהִיא – לְעִנְיַן אִיחַיּוֹבֵי מִיתָה וָחוֹמֶשׁ, דְּאִי תָּלֵישׁ וְאָכֵיל – תָּלוּשׁ הוּא, וְאִי גָּחֵין וְאָכֵיל – בָּטְלָה דַּעְתּוֹ אֵצֶל כׇּל אָדָם.
*Translation:* Abaye **said to** one of those Sages: **When that** *baraita* **is taught,** it is taught with regard to *teruma*, which renders a non-priest **liable to death** at the hand of Heaven **or** payment of **a fifth.** If a non-priest ate *teruma* intentionally he is liable to receive death at the hand of Heaven; if he ate it unintentionally, he must restore the amount he ate with the addition of one-fifth (see Leviticus 22:9, 14). The reason there is no penalty for eating *teruma* that is attached to the ground is **that if one detaches** it **and eats** it, **it is** considered **detached. And if he stooped down and ate** it while it was attached to the ground he is not liable, as **his intention is** rendered **irrelevant by** the opinions of **all** other **people.** In other words, this is an abnormal manner of eating, for which one is not liable.

**12.**
*Hebrew/Aramaic:* וּמַאי שְׁנָא מִדִּכְתַב אַפִּינַקְסָא דְּאִילְפָא: בֵּיצֵי נִבְלַת הָעוֹף הַטָּהוֹר, מִקְצָתָן בַּחוּץ וּמִקְצָתָן בִּפְנִים – מִבִּפְנִים מְטַמְּאִין בְּגָדִים אַבֵּית הַבְּלִיעָה, מִבַּחוּץ אֵין מְטַמְּאִין בְּגָדִים אַבֵּית הַבְּלִיעָה.
*Translation:* The Gemara asks: In **what** way **is** this case **different from** the *halakha* **that is written on the tablet [*appinkesa*] of Ilfa:** With regard to **eggs** found with the **carcass of a kosher bird, some of them outside** the bird **and some of them inside** the bird, if one ate from those inner eggs directly **from inside** the bird, **they render** the **garments** of one who swallows them **ritually impure** when they are **in the throat.** If he removed those same eggs and ate **from** them when they were **outside** the bird, **they do not render** the **garments** of one who swallows them **ritually impure** when they are **in the throat.** Apparently, even the abnormal method of eating eggs while they are inside the bird is still considered eating. If so, the same should apply to consuming *teruma* abnormally by stooping down and eating it while it is still attached to the ground.

**13.**
*Hebrew/Aramaic:* תָּלוּשׁ – עֲבִידִי אִינָשֵׁי דְּאָכְלִי הָכִי, בִּמְחוּבָּר – לָא עֲבִידִי אִינָשֵׁי דְּאָכְלִי.
*Translation:* The Gemara answers: With regard to an item that is **detached,** i.e., the eggs inside the bird, it is relatively **common for people to eat** even in **this** manner. But **with regard to** an item that is **attached** to the ground, it is **not common for people to eat** such produce at all.

**14.**
*Hebrew/Aramaic:* אָמַר רַב טָבְיוֹמֵי בַּר קִיסְנָא, אָמַר שְׁמוּאֵל: הַזּוֹרֵעַ כִּלְאַיִם בְּעָצִיץ שֶׁאֵינוֹ נָקוּב – אָסוּר. אָמַר אַבָּיֵי: בִּשְׁלָמָא אִי אַשְׁמְעִינַן לוֹקֶה מַכַּת מַרְדּוּת מִדְּרַבָּנַן – שַׁפִּיר, אֶלָּא אָסוּר – מַאי קָא מַשְׁמַע לַן?
*Translation:* § **Rav Tavyumei bar Kisna says** that **Shmuel says:** With regard to **one who plants diverse kinds** of plants **in a non-perforated flowerpot,** this is **prohibited. Abaye said:** What is novel about this *halakha*? **Granted if** Shmuel had **taught us** that one who plants in this manner **is flogged** with **lashes for rebelliousness by rabbinic law,** it is **well** and understandable. **But** with this basic ruling he stated, that it is **prohibited, what is** he **teaching us?**

**15.**
*Hebrew/Aramaic:* דְּמִדְּרַבָּנַן הָוְיָא זְרִיעָה? תְּנֵינָא: תָּרַם מִשֶּׁאֵינוֹ נָקוּב עַל הַנָּקוּב – תְּרוּמָה, וְיַחְזוֹר וְיִתְרוֹם.
*Translation:* Is he teaching **that** planting in a non-perforated flowerpot **is** considered **sowing by rabbinic law? We** already **learn** this in a mishna (*Demai* 5:10): If one **separated *teruma* from** produce grown in **a non-perforated** pot **for** produce of **a perforated** pot, it is ***teruma*** by rabbinic law, **and he must again separate *teruma*** from the produce obligated in *teruma* by Torah law to render the produce grown in the perforated pot permitted in consumption. Since this separation has the status of *teruma* by rabbinic law, evidently sowing in a non-perforated pot is considered sowing.

**16.**
*Hebrew/Aramaic:* מַתְנִי׳ הַחִיטִּין, וְהַשְּׂעוֹרִין, וְהַכּוּסְּמִין, וְהַשִּׁיבּוֹלֶת שׁוּעָל, וְהַשִּׁיפוֹן – הֲרֵי אֵלּוּ חַיָּיבִין בַּחַלָּה, וּמִצְטָרְפִין זֶה עִם זֶה, וַאֲסוּרִים בֶּחָדָשׁ מִלִּפְנֵי הַפֶּסַח, וּמִלִּקְצוֹר מִלִּפְנֵי הָעוֹמֶר. אִם הִשְׁרִישׁוּ קוֹדֶם לָעוֹמֶר – הָעוֹמֶר מַתִּירָן, וְאִם לָאו – אֲסוּרִין עַד שֶׁיָּבֹא הָעוֹמֶר הַבָּא.
*Translation:* MISHNA: **Wheat, barley, spelt, oats, and rye; these are obligated in** the separation of ***ḥalla*, and** each **one** of them **joins together with the others** to constitute the measure that obligates one to separate *ḥalla*. **And they are prohibited** due to the prohibition of partaking **of** the **new** crop **prior to the Passover** Festival, **and** likewise it is prohibited **to reap** them **prior to the *omer*** offering. **If** these grains **took root prior to the *omer*** offering, **the *omer* permits their** consumption; **and if not, they are prohibited until the next *omer* is brought** and sacrificed the following year.

**17.**
*Hebrew/Aramaic:* גְּמָ׳ תָּנָא: כּוּסְּמִין – מִין חִיטִּים, שִׁיבּוֹלֶת שׁוּעָל וְשִׁיפוֹן – מִין שְׂעוֹרִין. כּוּסְּמִין –
*Translation:* GEMARA: The Gemara discusses the identity of the species mentioned in the mishna. A Sage **taught** in a *baraita*: **Spelt** is **a type of wheat,** while **oats and rye** are **a type of barley.** The Gemara translates the lesser-known species into the vernacular Aramaic: **Spelt** is called
