-- Per-daf study aids (outline, charts, pictures, key terms), generated by daf-processor's
-- outline pass and loaded by daf-processor/upload_study_aids.py. Run once in the Supabase SQL editor.
-- tractate/daf follow shiur_content's convention (daf 31.5 = the "31b" shiur).
-- Illustration SVG is sanitized before upload (clean_svg + uniquify_ids).

create table if not exists daf_study_aids (
  tractate       text not null,
  daf            numeric(4,1) not null,
  outline        jsonb not null,               -- sections tree, scope; editorial notes stripped
  key_terms      jsonb,                        -- [{term, hebrew, sense, definition, on_this_daf, aliases, sections}]
  model          text not null,                -- e.g. claude-opus-5-5, or 'author example'
  prompt_version text not null,
  status         text not null default 'draft',  -- draft | reviewed | published
  generated_at   timestamptz default now(),
  primary key (tractate, daf)
);

-- Not public yet: the outlines are under review. Only the service role reads or writes
-- (RLS on, no policies). Add a read policy for status = 'published' when the web app goes live.
alter table daf_study_aids enable row level security;
