#!/bin/bash
# Re-run segmentation (pass 1) for 302 daf(im) with timestamp violations
# Generated by check_segmentation.py

# All located SRT files — processed in parallel
python3 main.py \
    "srt/processed/Hullin 22.srt" \
    "srt/processed/Hullin 9.srt" \
    "srt/processed/Arakhin 11.srt" \
    "srt/processed/Arakhin 13.srt" \
    "srt/processed/Arakhin 9.srt" \
    "srt/processed/Avodah Zarah 13.srt" \
    "srt/processed/Avodah Zarah 2.srt" \
    "srt/processed/Avodah Zarah 21.srt" \
    "srt/processed/Avodah Zarah 50.srt" \
    "srt/processed/Avodah Zarah 55.srt" \
    "srt/processed/Avodah Zarah 6.srt" \
    "srt/processed/Avodah Zarah 63.srt" \
    "srt/processed/Bava Batra 14.srt" \
    "srt/processed/Bava Batra 15.srt" \
    "srt/processed/Bava Batra 169.srt" \
    "srt/processed/Bava Batra 176.srt" \
    "srt/processed/Bava Batra 24.srt" \
    "srt/processed/Bava Batra 4.srt" \
    "srt/processed/Bava Batra 5.srt" \
    "srt/processed/Bava Batra 63.srt" \
    "srt/processed/Bava Batra 84.srt" \
    "srt/processed/Bava Kamma 115.srt" \
    "srt/processed/Bava Kamma 118.srt" \
    "srt/processed/Bava Kamma 23.srt" \
    "srt/processed/Bava Kamma 87.srt" \
    "srt/processed/Bava Kamma 98.srt" \
    "srt/processed/Bava Metzia 10.srt" \
    "srt/processed/Bava Metzia 100.srt" \
    "srt/processed/Bava Metzia 101.srt" \
    "srt/processed/Bava Metzia 16.srt" \
    "srt/processed/Bava Metzia 30.srt" \
    "srt/processed/Bava Metzia 31.srt" \
    "srt/processed/Bava Metzia 34.srt" \
    "srt/processed/Bava Metzia 44.srt" \
    "srt/processed/Bava Metzia 52.srt" \
    "srt/processed/Bava Metzia 54.srt" \
    "srt/processed/Bava Metzia 59.srt" \
    "srt/processed/Bava Metzia 62.srt" \
    "srt/processed/Bava Metzia 86.srt" \
    "srt/processed/Beitzah 15.srt" \
    "srt/processed/Beitzah 3.srt" \
    "srt/processed/Bekhorot 13.srt" \
    "srt/processed/Bekhorot 17.srt" \
    "srt/processed/Bekhorot 2.srt" \
    "srt/processed/Bekhorot 29.srt" \
    "srt/processed/Bekhorot 40b.srt" \
    "srt/processed/Bekhorot 40b.srt" \
    "srt/processed/Bekhorot 45b.srt" \
    "srt/processed/Bekhorot 52.srt" \
    "srt/processed/Berakhot 12b.srt" \
    "srt/processed/Berakhot 15b.srt" \
    "srt/processed/Berakhot 24b.srt" \
    "srt/processed/Berakhot 27b.srt" \
    "srt/processed/Berakhot 29.srt" \
    "srt/processed/Berakhot 4.srt" \
    "srt/processed/Berakhot 5.srt" \
    "srt/processed/Berakhot 53b.srt" \
    "srt/processed/Chagigah 16.srt" \
    "srt/processed/Eiruvin 82.srt" \
    "srt/processed/Gittin 19.srt" \
    "srt/processed/Gittin 25.srt" \
    "srt/processed/Gittin 28.srt" \
    "srt/processed/Gittin 36.srt" \
    "srt/processed/Gittin 37.srt" \
    "srt/processed/Gittin 39.srt" \
    "srt/processed/Gittin 45.srt" \
    "srt/processed/Gittin 57.srt" \
    "srt/processed/Gittin 60.srt" \
    "srt/processed/Gittin 65.srt" \
    "srt/processed/Gittin 66b.srt" \
    "srt/processed/Gittin 68.srt" \
    "srt/processed/Gittin 7.srt" \
    "srt/processed/Gittin 84.srt" \
    "srt/processed/Gittin 88.srt" \
    "srt/processed/Gittin 90.srt" \
    "srt/processed/Horayot 11.srt" \
    "srt/processed/Horayot 2.srt" \
    "srt/processed/Horayot 5.srt" \
    "srt/processed/Horayot 9.srt" \
    "srt/processed/Hullin 10.srt" \
    "srt/processed/Hullin 100.srt" \
    "srt/processed/Hullin 106.srt" \
    "srt/processed/Hullin 108.srt" \
    "srt/processed/Hullin 115.srt" \
    "srt/processed/Hullin 129.srt" \
    "srt/processed/Hullin 133.srt" \
    "srt/processed/Hullin 135.srt" \
    "srt/processed/Hullin 136.srt" \
    "srt/processed/Hullin 140.srt" \
    "srt/processed/Hullin 19.srt" \
    "srt/processed/Hullin 39.srt" \
    "srt/processed/Hullin 79.srt" \
    "srt/processed/Hullin 80.srt" \
    "srt/processed/Hullin 81.srt" \
    "srt/processed/Hullin 84.srt" \
    "srt/processed/Keritot 10.srt" \
    "srt/processed/Keritot 12.srt" \
    "srt/processed/Keritot 13.srt" \
    "srt/processed/Keritot 3b.srt" \
    "srt/processed/Keritot 4.srt" \
    "srt/processed/Keritot 9.srt" \
    "srt/processed/Ketubot 10.srt" \
    "srt/processed/Ketubot 105.srt" \
    "srt/processed/Ketubot 13.srt" \
    "srt/processed/Ketubot 17.srt" \
    "srt/processed/Ketubot 2.srt" \
    "srt/processed/Ketubot 37.srt" \
    "srt/processed/Ketubot 39.srt" \
    "srt/processed/Ketubot 43.srt" \
    "srt/processed/Ketubot 50.srt" \
    "srt/processed/Ketubot 55.srt" \
    "srt/processed/Kiddushin 37.srt" \
    "srt/processed/Kiddushin 4.srt" \
    "srt/processed/Kiddushin 42.srt" \
    "srt/processed/Kiddushin 44.srt" \
    "srt/processed/Kiddushin 45b.srt" \
    "srt/processed/Kiddushin 58.srt" \
    "srt/processed/Kiddushin 62.srt" \
    "srt/processed/Kiddushin 69.srt" \
    "srt/processed/Kiddushin 72.srt" \
    "srt/processed/Kiddushin 76.srt" \
    "srt/processed/Kiddushin 81.srt" \
    "srt/processed/Kinnim 23.srt" \
    "srt/processed/Makkot 11.srt" \
    "srt/processed/Makkot 21.srt" \
    "srt/processed/Makkot 24.srt" \
    "srt/processed/Meilah 6.srt" \
    "srt/processed/Menachot 36.srt" \
    "srt/processed/Menachot 49.srt" \
    "srt/processed/Menachot 61.srt" \
    "srt/processed/Menachot 62.srt" \
    "srt/processed/Menachot 71.srt" \
    "srt/processed/Menachot 79.srt" \
    "srt/processed/Menachot 8.srt" \
    "srt/processed/Menachot 81.srt" \
    "srt/processed/Menachot 91.srt" \
    "srt/processed/Menachot 92.srt" \
    "srt/processed/Menachot 95.srt" \
    "srt/processed/Menachot 99.srt" \
    "srt/processed/Middot 37.srt" \
    "srt/processed/Nazir 4.srt" \
    "srt/processed/Nazir 41.srt" \
    "srt/processed/Nazir 44b.srt" \
    "srt/processed/Nazir 47.srt" \
    "srt/processed/Nazir 56b.srt" \
    "srt/processed/Nazir 56b.srt" \
    "srt/processed/Nazir 60.srt" \
    "srt/processed/Nazir 8.srt" \
    "srt/processed/Nedarim 11.srt" \
    "srt/processed/Nedarim 29.srt" \
    "srt/processed/Nedarim 3.srt" \
    "srt/processed/Nedarim 38.srt" \
    "srt/processed/Nedarim 49.srt" \
    "srt/processed/Nedarim 50.srt" \
    "srt/processed/Nedarim 54.srt" \
    "srt/processed/Nedarim 75.srt" \
    "srt/processed/Nedarim 83.srt" \
    "srt/processed/Niddah 21.srt" \
    "srt/processed/Niddah 24.srt" \
    "srt/processed/Niddah 28.srt" \
    "srt/processed/Niddah 29.srt" \
    "srt/processed/Niddah 37.srt" \
    "srt/processed/Niddah 39.srt" \
    "srt/processed/Niddah 41.srt" \
    "srt/processed/Niddah 5.srt" \
    "srt/processed/Niddah 51.srt" \
    "srt/processed/Niddah 52.srt" \
    "srt/processed/Niddah 56.srt" \
    "srt/processed/Niddah 64.srt" \
    "srt/processed/Niddah 65.srt" \
    "srt/processed/Pesachim 102.srt" \
    "srt/processed/Pesachim 108.srt" \
    "srt/processed/Pesachim 112.srt" \
    "srt/processed/Pesachim 117.srt" \
    "srt/processed/Pesachim 118.srt" \
    "srt/processed/Pesachim 48.srt" \
    "srt/processed/Pesachim 69.srt" \
    "srt/processed/Pesachim 81.srt" \
    "srt/processed/Pesachim 82.srt" \
    "srt/processed/Pesachim 87.srt" \
    "srt/processed/Pesachim 88.srt" \
    "srt/processed/Pesachim 96.srt" \
    "srt/processed/Rosh Hashanah 11.srt" \
    "srt/processed/Rosh Hashanah 14.srt" \
    "srt/processed/Rosh Hashanah 17.srt" \
    "srt/processed/Rosh Hashanah 18.srt" \
    "srt/processed/Rosh Hashanah 33.srt" \
    "srt/processed/Rosh Hashanah 6.srt" \
    "srt/processed/Sanhedrin 111.srt" \
    "srt/processed/Sanhedrin 113.srt" \
    "srt/processed/Sanhedrin 24.srt" \
    "srt/processed/Sanhedrin 27.srt" \
    "srt/processed/Sanhedrin 37.srt" \
    "srt/processed/Sanhedrin 4.srt" \
    "srt/processed/Sanhedrin 54.srt" \
    "srt/processed/Sanhedrin 58.srt" \
    "srt/processed/Sanhedrin 67.srt" \
    "srt/processed/Sanhedrin 76.srt" \
    "srt/processed/Sanhedrin 79.srt" \
    "srt/processed/Sanhedrin 83.srt" \
    "srt/processed/Sanhedrin 84.srt" \
    "srt/processed/Sanhedrin 85.srt" \
    "srt/processed/Shabbat 113b.srt" \
    "srt/processed/Shabbat 12.srt" \
    "srt/processed/Shabbat 134.srt" \
    "srt/processed/Shabbat 146.srt" \
    "srt/processed/Shabbat 154.srt" \
    "srt/processed/Shabbat 18.srt" \
    "srt/processed/Shabbat 43.srt" \
    "srt/processed/Shabbat 51.srt" \
    "srt/processed/Shabbat 70.srt" \
    "srt/processed/Shabbat 81.srt" \
    "srt/processed/Shabbat 98.srt" \
    "srt/processed/Shabbat 99.srt" \
    "srt/processed/Shekalim 13.srt" \
    "srt/processed/Shekalim 20.srt" \
    "srt/processed/Shekalim 3.srt" \
    "srt/processed/Shekalim 4.srt" \
    "srt/processed/Shekalim 5.srt" \
    "srt/processed/Shevuot 21.srt" \
    "srt/processed/Shevuot 23.srt" \
    "srt/processed/Shevuot 29.srt" \
    "srt/processed/Shevuot 3.srt" \
    "srt/processed/Shevuot 30.srt" \
    "srt/processed/Shevuot 31.srt" \
    "srt/processed/Shevuot 39.srt" \
    "srt/processed/Shevuot 41.srt" \
    "srt/processed/Shevuot 42.srt" \
    "srt/processed/Shevuot 48.srt" \
    "srt/processed/Sotah 13.srt" \
    "srt/processed/Sotah 2.srt" \
    "srt/processed/Sotah 30.srt" \
    "srt/processed/Sotah 35.srt" \
    "srt/processed/Sotah 38.srt" \
    "srt/processed/Sotah 45.srt" \
    "srt/processed/Sotah 49.srt" \
    "srt/processed/Sukkah 16.srt" \
    "srt/processed/Sukkah 18.srt" \
    "srt/processed/Sukkah 20.srt" \
    "srt/processed/Sukkah 25.srt" \
    "srt/processed/Tamid 32.srt" \
    "srt/processed/Tamid 33b.srt" \
    "srt/processed/Temurah 13.srt" \
    "srt/processed/Temurah 17.srt" \
    "srt/processed/Temurah 20.srt" \
    "srt/processed/Temurah 21.srt" \
    "srt/processed/Temurah 26.srt" \
    "srt/processed/Temurah 3.srt" \
    "srt/processed/Temurah 33.srt" \
    "srt/processed/Temurah 5.srt" \
    "srt/processed/Yevamot 107.srt" \
    "srt/processed/Yevamot 108.srt" \
    "srt/processed/Yevamot 110.srt" \
    "srt/processed/Yevamot 121.srt" \
    "srt/processed/Yevamot 14.srt" \
    "srt/processed/Yevamot 19.srt" \
    "srt/processed/Yevamot 26b.srt" \
    "srt/processed/Yevamot 29b.srt" \
    "srt/processed/Yevamot 32.srt" \
    "srt/processed/Yevamot 32b.srt" \
    "srt/processed/Yevamot 57.srt" \
    "srt/processed/Yevamot 72.srt" \
    "srt/processed/Yevamot 82.srt" \
    "srt/processed/Yevamot 95.srt" \
    "srt/processed/Yoma 24.srt" \
    "srt/processed/Yoma 25.srt" \
    "srt/processed/Yoma 27.srt" \
    "srt/processed/Yoma 41.srt" \
    "srt/processed/Yoma 6.srt" \
    "srt/processed/Yoma 63.srt" \
    "srt/processed/Yoma 67.srt" \
    "srt/processed/Yoma 74.srt" \
    "srt/processed/Yoma 82.srt" \
    "srt/processed/Yoma 84.srt" \
    "srt/processed/Zevachim 104.srt" \
    "srt/processed/Zevachim 108.srt" \
    "srt/processed/Zevachim 116.srt" \
    "srt/processed/Zevachim 119.srt" \
    "srt/processed/Zevachim 13.srt" \
    "srt/processed/Zevachim 27.srt" \
    "srt/processed/Zevachim 29.srt" \
    "srt/processed/Zevachim 44.srt" \
    "srt/processed/Zevachim 59.srt" \
    "srt/processed/Zevachim 60.srt" \
    "srt/processed/Zevachim 76.srt" \
    "srt/processed/Zevachim 77.srt" \
    "srt/processed/Zevachim 8.srt" \
    "srt/processed/Zevachim 95.srt" \
    --workers 5

# ── SRT files not found — fix path and run individually ──
# Eruvin 22a-b: SRT not found
# python3 main.py "<PATH TO Eruvin 22a-b.srt>" --masechta "Eruvin" --daf 22 --amud a-b

# Eruvin 3b: SRT not found
# python3 main.py "<PATH TO Eruvin 3b.srt>" --masechta "Eruvin" --daf 3 --amud b

# Eruvin 48: SRT not found
# python3 main.py "<PATH TO Eruvin 48.srt>" --masechta "Eruvin" --daf 48

# Eruvin 54: SRT not found
# python3 main.py "<PATH TO Eruvin 54.srt>" --masechta "Eruvin" --daf 54

# Eruvin 77: SRT not found
# python3 main.py "<PATH TO Eruvin 77.srt>" --masechta "Eruvin" --daf 77

# Eruvin 86a-b: SRT not found
# python3 main.py "<PATH TO Eruvin 86a-b.srt>" --masechta "Eruvin" --daf 86 --amud a-b

# Eruvin 9bet: SRT not found
# python3 main.py "<PATH TO Eruvin 9bet.srt>" --masechta "Eruvin" --daf 9 --amud bet

# Eruvin 90b: SRT not found
# python3 main.py "<PATH TO Eruvin 90b.srt>" --masechta "Eruvin" --daf 90 --amud b

# Eruvin 91b: SRT not found
# python3 main.py "<PATH TO Eruvin 91b.srt>" --masechta "Eruvin" --daf 91 --amud b

# Megillah 11a: SRT not found
# python3 main.py "<PATH TO Megillah 11a.srt>" --masechta "Megillah" --daf 11 --amud a

# Megillah 31a: SRT not found
# python3 main.py "<PATH TO Megillah 31a.srt>" --masechta "Megillah" --daf 31 --amud a

# Taanit 18a: SRT not found
# python3 main.py "<PATH TO Taanit 18a.srt>" --masechta "Taanit" --daf 18 --amud a

# Taanit 22: SRT not found
# python3 main.py "<PATH TO Taanit 22.srt>" --masechta "Taanit" --daf 22

# Taanit 8a: SRT not found
# python3 main.py "<PATH TO Taanit 8a.srt>" --masechta "Taanit" --daf 8 --amud a

